---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "yandex-cloud-controller.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:{{ include "yandex-cloud-controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yandex-cloud-controller.name" . }}
    namespace: {{ .Release.Namespace }}
