
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yandex-cloud-controller.name" . }}
data:
  serviceAccountJSON: {{ .Values.serviceAccountJSON }}
  folderID: {{ .Values.folderID }}
  vpcID: {{ .Values.vpcID }}
  routeTableID: {{ .Values.routeTableID }}
